# Generated by Django 4.1.2 on 2023-02-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_alter_benefactor_user_alter_charity_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='charities.benefactor'),
        ),
    ]
